### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mstg** [CharizTeam/Helper#1]
## Helper roadmap
- [x] Check if Homebrew is installed
- [x] Install Homebrew if not
- [x] Install dpkg-chariz
